### ISSUE TITLE
Providing nil options causes a panic

### ISSUE THREAD

**Issue by sazzer** [nsf/jsondiff#13] opened 2021-06-02 07:00 UTC
The `Compare` method takes a parameter of `*Options`. However, providing a value of `nil` here causes a panic where it could work correctly.

This code works fine:
```
		options := jsondiff.DefaultJSONOptions()
		diff, _ := jsondiff.Compare(body, []byte(expected), &options)
```

Whereas this panics as below:
```
		diff, _ := jsondiff.Compare(body, []byte(expected), nil)
```

```
2021/06/02 07:55:55 http: panic serving 127.0.0.1:53003: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc00012cbe0)
	/Users/coxg/.gvm/gos/go1.16.4/src/net/http/server.go:1824 +0x153
panic(0x131a260, 0x1582ed0)
	/Users/coxg/.gvm/gos/go1.16.4/src/runtime/panic.go:971 +0x499
github.com/nsf/jsondiff.(*context).printDiff(0xc000117960, 0x1318660, 0xc00007f470, 0x1318660, 0xc00007f4d0)
	/Users/coxg/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/nsf/jsondiff@v0.0.0-20210303162244-6ea32392771e/jsondiff.go:340 +0x4ea
github.com/nsf/jsondiff.Compare(0xc000172000, 0x21, 0x200, 0xc000022390, 0x21, 0x30, 0x0, 0xc00005ba30, 0x1284b1f, 0x1346e60)
	/Users/coxg/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/nsf/jsondiff@v0.0.0-20210303162244-6ea32392771e/jsondiff.go:425 +0x296
github.com/sazzer/gomockserver.MatchJSON.func1(0xc000168200, 0xc00005ba01)
	/Users/coxg/source/me/gomockserver/json.go:32 +0x198
github.com/sazzer/gomockserver.MatchRuleFunc.Matches(0xc0000681a0, 0xc000168200, 0xc00005bb40)
	/Users/coxg/source/me/gomockserver/matchers.go:16 +0x30
github.com/sazzer/gomockserver.MatchRules.Matches(0xc00005ef80, 0x1, 0x1, 0xc000168200, 0x0)
	/Users/coxg/source/me/gomockserver/matchers.go:25 +0x68
github.com/sazzer/gomockserver.(*Match).Matches(...)
	/Users/coxg/source/me/gomockserver/match.go:13
github.com/sazzer/gomockserver.(*handler).ServeHTTP(0xc00000e198, 0x13e11d0, 0xc0001640e0, 0xc000168200)
	/Users/coxg/source/me/gomockserver/handler.go:13 +0xa5
net/http.serverHandler.ServeHTTP(0xc000164000, 0x13e11d0, 0xc0001640e0, 0xc000168200)
	/Users/coxg/.gvm/gos/go1.16.4/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00012cbe0, 0x13e1800, 0xc00002e980)
	/Users/coxg/.gvm/gos/go1.16.4/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/Users/coxg/.gvm/gos/go1.16.4/src/net/http/server.go:3013 +0x39b
```

Cheers

**Comment by nsf** [comment] 2021-09-18 09:19
Duplicate of https://github.com/nsf/jsondiff/issues/8.

Sorry, it's just bad naming. Options in this case are not optional indeed. Thinking about better name.

**Closed by nsf** 2021-09-18 09:19 UTC
